### ISSUE TITLE
add the static margin as a constraint 

### ISSUE THREAD

**Issue by zhuwenguo** [DAFoam/DAFoam.github.io#34]
I am learning to use DaFoam to optimize a flying wing, I need to add the longitudinal stability as a constraint which was calculated as the moment and lift derivatives with respect to the angle-of-attack. how to add the calculation the derivatives in DaFoam, could anyone please give some tips or tutorials? thanks.

**Comment by friedenhe** [comment]
@zhuwenguo I moved your question to the DAFoam repo discussion. Check [here](https://github.com/mdolab/dafoam/discussions/400)
